services:
  master:
    image: jupyter-notebook:latest
    container_name: spark_master
    build:
      context: .
      args:
        PYTHON_VERSION: "3.9-slim"
    profiles: ["master"]
    ports:
      - "8888:8888"    # Jupyter Notebook
      - "5001:5000"    # MLflow UI
      - "7077:7077"    # Spark Master Comm
      - "8080:8080"    # Spark Master Web UI
      - "4040:4040"    # Spark Application UI
    volumes:
      - /opt/jupyter:/home/jovyan/work
      - /opt/mlflow:/mlflow
    environment:
      - SPARK_ROLE=master
      - SPARK_DRIVER_HOST=10.8.1.13  # Or local IP for OpenVPN
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
      - PYSPARK_SUBMIT_ARGS=--jars /opt/spark/jars/delta-spark_2.12-3.1.0.jar,/opt/spark/jars/delta-storage-3.1.0.jar pyspark-shell
    command: ["/start.sh"]
    restart: unless-stopped

  worker:
    image: jupyter-notebook:latest
    container_name: spark_worker
    profiles: ["worker"]
    depends_on:
      - master
    volumes:
      - /opt/jupyter:/home/jovyan/work
    environment:
      - SPARK_ROLE=worker
      - SPARK_MASTER=spark://spark_master:7077
    command: ["/start.sh"]
    restart: unless-stopped
